global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'telegram-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'telegram-critical'
      continue: true
      group_wait: 10s
      repeat_interval: 1h

receivers:
  - name: 'telegram-notifications'
    telegram_configs:
    - bot_token: 'YOUR_TELEGRAM_BOT_TOKEN'
      api_url: 'https://api.telegram.org'
      chat_id: YOUR_CHAT_ID
      parse_mode: 'HTML'
      message: |
        🔔 <b>{{ .Status | toUpper }}</b>
        <b>Alert:</b> {{ .CommonAnnotations.summary }}
        <b>Description:</b> {{ .CommonAnnotations.description }}
        <b>Severity:</b> {{ .CommonLabels.severity }}
        <b>Affected Instances:</b>
        {{- range .Alerts }}
          {{ .Labels.instance }}
        {{- end }}

  - name: 'telegram-critical'
    telegram_configs:
    - bot_token: 'YOUR_TELEGRAM_BOT_TOKEN'
      api_url: 'https://api.telegram.org'
      chat_id: YOUR_CHAT_ID
      parse_mode: 'HTML'
      message: |
        🚨 <b>CRITICAL ALERT</b> 🚨
        <b>Alert:</b> {{ .CommonAnnotations.summary }}
        <b>Description:</b> {{ .CommonAnnotations.description }}
        <b>Severity:</b> {{ .CommonLabels.severity }}
        <b>Affected Instances:</b>
        {{- range .Alerts }}
          {{ .Labels.instance }}
        {{- end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']