version: '3.8'

services:
  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml.template:/etc/prometheus/prometheus.yml.template
      - ./prometheus/rules:/etc/prometheus/rules
      - prometheus_data:/prometheus
    environment:
      - HASHED_PASSWORD=${PROM_PASSWORD}
      - NODE_EXPORTER_TARGETS=${NODE_EXPORTER_TARGETS}
    entrypoint:
      - /bin/sh
      - -c
      - |
        envsubst --version && \
        envsubst < /etc/prometheus/prometheus.yml.template > /etc/prometheus/prometheus.yml && \
        prometheus \
          --config.file=/etc/prometheus/prometheus.yml \
          --storage.tsdb.path=/prometheus \
          --storage.tsdb.retention.time=15d \
          --web.console.libraries=/etc/prometheus/console_libraries \
          --web.console.templates=/etc/prometheus/consoles \
          --web.enable-lifecycle
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    ports:
      - "9093:9093"
    restart: unless-stopped
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=localhost
      - GF_SMTP_ENABLED=false
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
    driver: local
    driver_opts:
      type: none
      device: ${PROMETHEUS_PERSIST_PATH}
      o: bind
  alertmanager_data:
    driver: local
    driver_opts:
      type: none
      device: ${ALERTMANAGER_PERSIST_PATH}
      o: bind
  grafana_data:
    driver: local
    driver_opts:
      type: none
      device: ${GRAFANA_PERSIST_PATH}
      o: bind
