apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: "${PROMETHEUS_URL}"
    basicAuth: true
    basicAuthUser: "${PROMETHEUS_USER}"
    secureJsonData:
      basicAuthPassword: "${PROMETHEUS_PASSWORD}"
    isDefault: true
    editable: false